package br.com.aspenmc.bukkit.antihax;

public enum CheatType {

    REACH, KILLAURA, AIM, AUTOCLICKER, VELOCITY, FLY, SPEED, JESUS, MOTION, INVENTORY, SCAFFOLD, NOFALL, BLOCK,
    BADPACKETS, TIMER, AUTOSOUP;

}
