serverId: proxy.aspenmc.com.br

motds:
  server-not-found:
    header: '&6&lAspenMC &8&l» &7&lO servidor não foi encontrado.'
    footer: '&7O servidor que você tentou acessar não foi encontrado.'
  maintenance:
    header: '&6&lAspenMC &8&l» &7&lO servidor está em manutenção.'
    footer: '&7Estamos trabalhando para melhorar sua experiência.'
  random:
    principal:
      header: '&6&lAspenMC &8&l» &7&lTest'
      footer: '&7This is a test motd.'
    second:
      header: '&6&lAspenMC &8&l» &7&lTest 2'
      footer: '&7This is a test motd. 2'